-- ADMIN --

CREATE USER 'admin02'@'localhost' IDENTIFIED BY 'admin02'; -- CREA UN USUARIO

GRANT ALL PRIVILEGES ON *.* TO 'admin02'@'localhost' WITH GRANT OPTION; -- ESTABLECE PERMISOS

-- USUARIO NORMAL --

CREATE USER 'user02'@'localhost' IDENTIFIED BY 'user02'; -- CREA UN USUARIO

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE
ON *.* TO 'user02'@'localhost'; -- ESTABLECE PERMISOS

-- USUARIO DE SOLO LECTURA --

CREATE USER 'read01'@'localhost' IDENTIFIED BY 'read01'; -- CREA UN USUARIO

GRANT SELECT, EXECUTE
ON *.* TO 'read01'@'localhost'; -- ESTABLECE PERMISOS

-- USUARIO PARA BACKUP --

CREATE USER 'back01'@'localhost' IDENTIFIED BY 'back01'; -- CREA UN USUARIO

GRANT RELOAD, LOCK TABLES, REPLICATION CLIENT
ON *.* TO 'back01'@'localhost'; -- ESTABLECE PERMISOS