CREATE DATABASE ventas_jugos CHARSET utf32;
USE ventas_jugos;

CREATE TABLE tb_vendedor
(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
VACACIONES BIT(1) NULL,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE tb_producto
(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

/* DROP TABLE tb_clientes; */

CREATE TABLE tb_clientes
(
DNI VARCHAR (11) NOT NULL,
NOMBRE VARCHAR (100) DEFAULT NULL,
DIRECCION VARCHAR(150) DEFAULT NULL,
BARRIO VARCHAR (50) DEFAULT NULL,
CIUDAD VARCHAR (50) DEFAULT NULL,
ESTADO VARCHAR (50) DEFAULT NULL,
CP INT(8) DEFAULT NULL,
FECHA_NACIMIENTO DATE DEFAULT NULL,
EDAD INT(3) DEFAULT NULL,
SEXO VARCHAR(1) DEFAULT NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUMEN_COMPRA FLOAT DEFAULT NULL,
PRIMERA_COMPRA BIT(1) DEFAULT NULL,
PRIMARY KEY (DNI)
);

ALTER TABLE facturas RENAME tb_ventas;

ALTER TABLE tb_ventas ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (DNI) REFERENCES tb_clientes(DNI);

ALTER TABLE tb_ventas ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA);

CREATE TABLE items_facturas
(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE items_facturas RENAME tb_items_facturas;

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_FACTURAS FOREIGN KEY (NUMERO) REFERENCES tb_facturas(NUMERO);

ALTER TABLE tb_ventas ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (DNI) REFERENCES tb_clientes(DNI);

ALTER TABLE tb_ventas ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedores(MATRICULA);

DROP DATABASE ventas_jugos;

/* -------- NUEVO ---------- */

CREATE DATABASE ventas_jugos;

CREATE SCHEMA IF NOT EXISTS ventas_jugos2 DEFAULT CHARSET utf32;

DROP DATABASE ventas_jugos2;

USE ventas_jugos;

CREATE TABLE tb_producto(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL,
PRIMARY KEY(MATRICULA)
);

CREATE TABLE tb_cliente
(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100),
DIRECCION VARCHAR(150),
BARRIO VARCHAR(50),
CIUDAD VARCHAR(50),
ESTADO VARCHAR(10),
CP VARCHAR (10),
FECHA_NACIMIENTO DATE,
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT(1),
PRIMARY KEY (DNI)
);

CREATE TABLE tb_items_facturas
(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10),
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY (NUMERO)
);

CREATE TABLE tb_venta(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO)
);

ALTER TABLE tb_venta ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (DNI) REFERENCES tb_cliente(DNI);

ALTER TABLE tb_venta ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA);

ALTER TABLE tb_venta RENAME tb_factura;

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_FACTURA
FOREIGN KEY (NUMERO) REFERENCES tb_factura(NUMERO);

ALTER TABLE tb_items_facturas ADD CONSTRAINT FK_PRODUCTO
FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO);

INSERT INTO tb_producto (CODIGO, DESCRIPCION, SABOR, TAMANO, ENVASE, PRECIO_LISTA) 
VALUES 
(
'10203040',
'Light',
'Sandia',
'350 ml',
'Lata',
4.56
);

SELECT * FROM tb_producto;

INSERT INTO tb_producto (CODIGO, SABOR, DESCRIPCION, TAMANO, ENVASE, PRECIO_LISTA) 
VALUES 
(
'10',
'Guanábana',
'Light',
'350 ml',
'Lata',
4
);

INSERT INTO tb_producto
VALUES 
(
'1020',
'Asaí',
'Light',
'350 ml',
'Lata',
5.60
),
(
'102040',
'Manzana',
'Light',
'350 ml',
'Lata',
6.00
),
(
'102030',
'Mango',
'Light',
'350 ml',
'Lata',
5.60
);

SELECT * FROM tb_producto;

INSERT INTO tb_cliente
(DNI, NOMBRE, DIRECCION, BARRIO, CIUDAD, ESTADO, CP, FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA, PRIMERA_COMPRA) 
VALUES 
('9283760794', 'Edson Calisaya', 'Sta Úrsula Xitla', 'Barrio del Niño Jesús', 'Ciudad de México', 'EM', '22002002', '1995-01-07', 25, 'M', 150000, 250000, 1),
('7771579779', 'Marcelo Perez', 'F.C. de Cuernavaca 13', 'Carola', 'CIUDAD: Ciudad de México', 'EM', '88202912', '1992-01-25', 29, 'M', 70000, 160000, 1), 
('5576228758', 'Patricia Olivera', 'Pachuca 75', 'Condesa', 'Ciudad de México', 'EM', '88192029', '1995-01-14', 25, 'F', 70000, 160000, 1);

SELECT * FROM tb_cliente;

SELECT * FROM jugos_ventas.tabla_de_productos;

SELECT CODIGO_DEL_PRODUCTO AS CODIGO, NOMBRE_DEL_PRODUCTO AS DESCRIPCION, SABOR, TAMANO, ENVASE, PRECIO_DE_LISTA AS PRECIO_LISTA
FROM jugos_ventas.tabla_de_productos;

SELECT CODIGO_DEL_PRODUCTO AS CODIGO, NOMBRE_DEL_PRODUCTO AS DESCRIPCION, SABOR, TAMANO, ENVASE, PRECIO_DE_LISTA AS PRECIO_LISTA
FROM jugos_ventas.tabla_de_productos
WHERE CODIGO_DEL_PRODUCTO NOT IN (SELECT CODIGO FROM tb_producto);

INSERT INTO tb_producto 
SELECT CODIGO_DEL_PRODUCTO AS CODIGO, NOMBRE_DEL_PRODUCTO AS DESCRIPCION, SABOR, TAMANO, ENVASE, PRECIO_DE_LISTA AS PRECIO_LISTA
FROM jugos_ventas.tabla_de_productos
WHERE CODIGO_DEL_PRODUCTO NOT IN (SELECT CODIGO FROM tb_producto);

SELECT * FROM tb_producto;

SELECT * FROM jugos_ventas.tabla_de_clientes;

INSERT INTO tb_cliente
SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION, BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO AS FECHA_NACIMIENTO, EDAD, SEXO, 
LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA, PRIMERA_COMPRA
FROM jugos_ventas.tabla_de_clientes
WHERE DNI NOT IN (SELECT DNI FROM tb_cliente);

SELECT * FROM tb_cliente;

SELECT COUNT(*) FROM tb_cliente;

SELECT * FROM tb_cliente;

SELECT * FROM tb_vendedor;

SELECT * FROM tb_producto;

UPDATE tb_producto SET PRECIO_LISTA = 5 WHERE CODIGO = '1000889';

UPDATE tb_producto SET DESCRIPCION = 'Sabor de la montaña', TAMANO = '1 Litro', ENVASE = 'Botella PET'
WHERE CODIGO = '1000889';

SELECT * FROM tb_producto;

SELECT * FROM tb_cliente;

UPDATE tb_cliente SET VOLUMEN_COMPRA = VOLUMEN_COMPRA/10;

SELECT * FROM tb_cliente;

SELECT * FROM tb_cliente WHERE DNI = '5840119709';

SELECT * FROM tb_vendedor;

SELECT * FROM tb_vendedor A
INNER JOIN
jugos_ventas.tabla_de_vendedores B
ON A.MATRICULA = SUBSTRING(B.MATRICULA, 3, 3);

UPDATE tb_cliente SET DIRECCION = 'Jorge Emilio 23', BARRIO = 'San Antonio', CIUDAD = 'Guadalajara', ESTADO = 'Jalisco',
CP = '44700000' WHERE DNI = '5840119709';

UPDATE tb_vendedor A
INNER JOIN
jugos_ventas.tabla_de_vendedores B
ON A.MATRICULA = SUBSTRING(B.MATRICULA, 3, 3)
SET A.DE_VACACIONES = B.VACACIONES;

SELECT * FROM tb_vendedor;

SELECT A.DNI FROM tb_cliente A
INNER JOIN tb_vendedor B
ON A.BARRIO = B.BARRIO;

UPDATE tb_cliente A 
INNER JOIN 
tb_vendedor B
ON A.BARRIO = B.BARRIO
SET A.VOLUMEN_COMPRA = A.VOLUMEN_COMPRA * 1.3;

SELECT * FROM tb_cliente;

INSERT INTO tb_producto (CODIGO,DESCRIPCION,SABOR,TAMANO,ENVASE,PRECIO_LISTA)
     VALUES ('1001001','Sabor Alpino','Mango','700 ml','Botella',7.50),
         ('1001000','Sabor Alpino','Melón','700 ml','Botella',7.50),
         ('1001002','Sabor Alpino','Guanábana','700 ml','Botella',7.50),
         ('1001003','Sabor Alpino','Mandarina','700 ml','Botella',7.50),
         ('1001004','Sabor Alpino','Banana','700 ml','Botella',7.50),
         ('1001005','Sabor Alpino','Asaí','700 ml','Botella',7.50),
         ('1001006','Sabor Alpino','Mango','1 Litro','Botella',7.50),
         ('1001007','Sabor Alpino','Melón','1 Litro','Botella',7.50),
         ('1001008','Sabor Alpino','Guanábana','1 Litro','Botella',7.50),
         ('1001009','Sabor Alpino','Mandarina','1 Litro','Botella',7.50),
         ('1001010','Sabor Alpino','Banana','1 Litro','Botella',7.50),
         ('1001011','Sabor Alpino','Asaí','1 Litro','Botella',7.50);

SELECT * FROM tb_producto WHERE DESCRIPCION = 'Sabor Alpino';

DELETE FROM tb_producto WHERE CODIGO = '1001000';

DELETE FROM tb_producto WHERE TAMANO = '1 litro';

SELECT CODIGO_DEL_PRODUCTO FROM jugos_ventas.tabla_de_productos;

SELECT CODIGO FROM tb_producto
WHERE CODIGO NOT IN (SELECT CODIGO_DEL_PRODUCTO FROM jugos_ventas.tabla_de_productos);

DELETE FROM tb_producto WHERE CODIGO NOT IN (SELECT CODIGO_DEL_PRODUCTO FROM jugos_ventas.tabla_de_productos);

DELETE A FROM tb_factura A
INNER JOIN 
tb_cliente B 
ON A.DNI = B.DNI
WHERE B.EDAD < 18;

CREATE TABLE `tb_producto2` (
  `CODIGO` varchar(10) NOT NULL,
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `SABOR` varchar(50) DEFAULT NULL,
  `TAMANO` varchar(50) DEFAULT NULL,
  `ENVASE` varchar(50) DEFAULT NULL,
  `PRECIO_LISTA` float DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM tb_producto2;

INSERT INTO tb_producto2 SELECT* FROM tb_producto;

UPDATE tb_producto2 SET PRECIO_LISTA = PRECIO_LISTA*1.15;

DELETE FROM tb_producto2;

INSERT INTO `ventas_jugos`.`tb_vendedor`
(`MATRICULA`,
`NOMBRE`,
`BARRIO`,
`COMISION`,
`FECHA_ADMISION`,
`DE_VACACIONES`)
VALUES
('256',
'Fernando Ruiz',
'Oblatos',
0.1,
'2015-06.14',
0);

SELECT * FROM tb_vendedor;

START TRANSACTION;

INSERT INTO `ventas_jugos`.`tb_vendedor`
(`MATRICULA`,
`NOMBRE`,
`BARRIO`,
`COMISION`,
`FECHA_ADMISION`,
`DE_VACACIONES`)
VALUES
('257',
'Fernando Rojas',
'Oblatos',
0.1,
'2015-06.14',
0);

UPDATE tb_vendedor SET COMISION = COMISION * 1.05;

ROLLBACK;

COMMIT;

CREATE TABLE tb_identificacion
(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(50),
PRIMARY KEY(ID)
);

SELECT * FROM tb_identificacion;

INSERT INTO tb_identificacion(DESCRIPCION) VALUES ('CLIENTE A');

INSERT INTO tb_identificacion(DESCRIPCION) VALUES ('CLIENTE B');

INSERT INTO tb_identificacion(DESCRIPCION) VALUES ('CLIENTE C');

DELETE FROM tb_identificacion WHERE ID = 1;

INSERT INTO tb_identificacion(DESCRIPCION) VALUES ('CLIENTE D');

INSERT INTO tb_identificacion(ID, DESCRIPCION) VALUES (100, 'CLIENTE D');

INSERT INTO tb_identificacion(DESCRIPCION) VALUES ('CLIENTE H');

CREATE TABLE tb_default
(
ID INT AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(100),
CIUDAD VARCHAR(50) DEFAULT 'Monterrey',
FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(ID)
);

INSERT INTO tb_default
(DESCRIPCION, DIRECCION, CIUDAD, FECHA_CREACION)
VALUES
('CLIENTE A', 'CALLE SOL NO. 525', 'CANCÚN', '2021-01-01');

SELECT * FROM tb_default;

INSERT INTO tb_default
(DESCRIPCION)
VALUES
('CLIENTE Y');

CREATE TABLE tb_facturacion
(
FECHA DATE,
VENTA_TOTAL FLOAT
);

SELECT * FROM tb_facturacion

CREATE TABLE `tb_factura1` (
  `NUMERO` varchar(5) NOT NULL,
  `FECHA` date DEFAULT NULL,
  `DNI` varchar(11) NOT NULL,
  `MATRICULA` varchar(5) NOT NULL,
  `IMPUESTO` float DEFAULT NULL,
  PRIMARY KEY (`NUMERO`),
  KEY `FK_CLIENTE1` (`DNI`),
  KEY `FK_VENDEDOR1` (`MATRICULA`),
  CONSTRAINT `FK_CLIENTE1` FOREIGN KEY (`DNI`) REFERENCES `tb_cliente` (`DNI`),
  CONSTRAINT `FK_VENDEDOR1` FOREIGN KEY (`MATRICULA`) REFERENCES `tb_vendedor` (`MATRICULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tb_items_facturas1` (
  `NUMERO` varchar(5) NOT NULL,
  `CODIGO` varchar(10) DEFAULT NULL,
  `CANTIDAD` int DEFAULT NULL,
  `PRECIO` float DEFAULT NULL,
  PRIMARY KEY (`NUMERO`),
  KEY `FK_PRODUCTO1` (`CODIGO`),
  CONSTRAINT `FK_FACTURA1` FOREIGN KEY (`NUMERO`) REFERENCES `tb_factura` (`NUMERO`),
  CONSTRAINT `FK_PRODUCTO1` FOREIGN KEY (`CODIGO`) REFERENCES `tb_producto` (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT * FROM tb_items_facturas1;
SELECT * FROM tb_factura1;
SELECT * FROM tb_cliente;
SELECT * FROM tb_vendedor;
SELECT * FROM tb_producto;

INSERT INTO tb_factura1
VALUES ('0100', '2021-01-01', '1471156710', '235', 0.10);

INSERT INTO tb_items_facturas1
VALUES ('12345', '1002767', 100, 25),
('54321', '1004327', 200, 25),
('2468', '1013793', 300, 25);

-- TRIGGERS

DELIMITER //

CREATE TRIGGER TG_FACTURACION_INSERT
AFTER INSERT ON tb_items_facturas1
FOR EACH ROW BEGIN

	DELETE FROM tb_factruacion;
	INSERT INTO tb_facturacion
	SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
	FROM tb_factura1 A 
	INNER JOIN
	tb_items_facturas1 B
	ON A.NUMERO = B.NUMERO
	GROUP BY A.FECHA;

END //

INSERT INTO tb_factura1
VALUES ('0103', '2021-01-02', '121423', '235', 0.10);
INSERT INTO tb_items_facturas1
VALUES
('0102', '101231', 200, 25),
('0103', '102461', 200, 25);

SELECT DNI, EDAD, FECHA_NACIMIENTO, timestampdiff(YEAR, FECHA_NACIMIENTO, NOW()) AS ANOS FROM tb_cliente;

DELIMITER //
CREATE TRIGGER TG_EDAD_CLIENTES_INSERT 
BEFORE INSERT ON tb_clientes
FOR EACH ROW BEGIN
SET NEW.EDAD = timestampdiff(YEAR, NEW.FECHA_NACIMIENTO, NOW());
END//
