USE jugos_ventas;
	
    -- CONSULTAS
    
    SELECT * FROM facturas;
    
    SELECT NOMBRE, DIRECCION_1, DIRECCION_2, BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO,
    EDAD, SEXO, LIMITE_DE_CREDITO, VOLUMEN_DE_COMPRA, PRIMERA_COMPRA FROM tabla_de_clientes;
    
    SELECT * FROM tabla_de_clientes;
    
    SELECT DNI, NOMBRE FROM tabla_de_clientes;
    
    SELECT DNI AS IDENTIFICACION, NOMBRE AS CLIENTE FROM tabla_de_clientes; -- AS (ALIAS)
    
    SELECT * FROM tabla_de_productos;
    
    SELECT * FROM tabla_de_productos WHERE SABOR = 'UVA'; -- WHERE (DONDE)
    
    SELECT * FROM tabla_de_productos WHERE SABOR = 'MANGO';
    
    SELECT * FROM tabla_de_productos WHERE ENVASE = 'BOTELLA PET';
    
    SELECT * FROM tabla_de_productos WHERE PRECIO_DE_LISTA > 16;
    
    SELECT * FROM tabla_de_productos WHERE PRECIO_DE_LISTA >= 17;
    
    SELECT * FROM tabla_de_productos WHERE PRECIO_DE_LISTA BETWEEN 16 AND 16.02; -- BETWEEN (ENTRE)
    
    -- CONSULTAS CON CONDICIONALES
    
    SELECT * FROM tabla_de_productos;
    
    SELECT * FROM tabla_de_productos WHERE SABOR = 'MANGO' AND TAMANO = '470 ML';
    
	SELECT * FROM tabla_de_productos WHERE SABOR = 'MANGO' OR TAMANO = '470 ML';
    
	SELECT * FROM tabla_de_productos WHERE NOT (SABOR = 'MANGO') OR TAMANO = '470 ML';
    
    SELECT * FROM tabla_de_productos WHERE NOT (SABOR = 'MANGO' AND TAMANO = '470 ML');
    
    SELECT * FROM tabla_de_productos WHERE SABOR = 'MANGO' AND NOT (TAMANO = '470 ML');
    
    SELECT * FROM tabla_de_productos WHERE SABOR IN ('MANGO', 'UVA'); -- IN (OR)
    SELECT * FROM tabla_de_productos WHERE SABOR = 'MANGO' OR 'UVA';
    
    SELECT * FROM tabla_de_clientes WHERE CIUDAD IN ('CIUDAD DE MÉXICO', 'GUADALAJARA');
    
    SELECT * FROM tabla_de_clientes WHERE CIUDAD IN ('CIUDAD DE MÉXICO', 'GUADALAJARA')
    AND (EDAD BETWEEN 20 AND 25);
    
    -- LIKE (REPRESENTA CUALQUIE REGISTRO GENERICO ANTES O DESPUES DE LA CONDICION)
    
    SELECT * FROM tabla_de_productos WHERE SABOR LIKE '%MANZANA';
    
    SELECT * FROM tabla_de_productos WHERE SABOR LIKE '%MANZANA' AND ENVASE = 'BOTELLA PET';
    
    SELECT * FROM tabla_de_clientes WHERE NOMBRE LIKE '%EZ';
    
    -- DISTINCT (RETORNA REGISTROS CON VALORES DIFERENTES)
    
    SELECT ENVASE, TAMANO FROM tabla_de_productos;
    
    SELECT DISTINCT ENVASE, TAMANO FROM tabla_de_productos; -- NO REPITE LOS REGISTROS
    
    SELECT DISTINCT ENVASE, TAMANO, SABOR FROM tabla_de_productos WHERE SABOR = 'NARANJA';
    
    SELECT DISTINCT BARRIO FROM TABLA_DE_CLIENTES WHERE CIUDAD = 'CIUDAD DE MÉXICO';
    
    -- LIMIT (LIMITA LOS REGISTROS)
    
    SELECT * FROM tabla_de_productos;
    
    SELECT * FROM tabla_de_productos LIMIT 5;
    
    SELECT * FROM tabla_de_productos LIMIT 5,4;
    
    SELECT * FROM FACTURAS;
    
    SELECT * FROM FACTURAS WHERE FECHA_VENTA = '2017-01-01' LIMIT 10;
    
    -- ORDER BY (ORDENA LOS REGISTROS)
    
    SELECT * FROM tabla_de_productos;
    
    SELECT * FROM tabla_de_productos ORDER BY PRECIO_DE_LISTA;
	
    SELECT * FROM tabla_de_productos ORDER BY PRECIO_DE_LISTA DESC;
    
    SELECT * FROM tabla_de_productos ORDER BY NOMBRE_DEL_PRODUCTO;
    
    SELECT * FROM tabla_de_productos ORDER BY NOMBRE_DEL_PRODUCTO DESC;
    
    SELECT * FROM tabla_de_productos ORDER BY ENVASE ASC, NOMBRE_DEL_PRODUCTO DESC;
    
    SELECT CODIGO_DEL_PRODUCTO FROM tabla_de_productos WHERE NOMBRE_DEL_PRODUCTO = 'REFRESCANTE' 
    AND TAMANO = '1 LITRO' AND SABOR = 'FRUTILLA/LIMON';
    
    SELECT * FROM items_facturas WHERE CODIGO_DEL_PRODUCTO = "1101035" ORDER BY CANTIDAD DESC;
    
    -- GROUP BY (AGRUPA VALORES)
    
    SELECT ESTADO, LIMITE_DE_CREDITO FROM tabla_de_clientes;

	SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO;
    
    SELECT ENVASE, PRECIO_DE_LISTA FROM tabla_de_productos;
    
    SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS MAYOR_PRECIO FROM tabla_de_productos GROUP BY ENVASE;
    
	SELECT ENVASE, COUNT(*) FROM tabla_de_productos GROUP BY ENVASE;
    
    SELECT BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes GROUP BY BARRIO;
    
    SELECT CIUDAD, BARRIO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabla_de_clientes WHERE CIUDAD = 'GUADALAJARA' 
    GROUP BY BARRIO;
    
    SELECT CIUDAD, BARRIO, AVG(LIMITE_DE_CREDITO) AS LIMITE_PROMEDIO FROM tabla_de_clientes WHERE CIUDAD = 'CIUDAD DE MEXICO' 
    GROUP BY BARRIO;
    
    SELECT ESTADO, BARRIO, MAX(LIMITE_DE_CREDITO) AS LIMITE, EDAD FROM tabla_de_clientes
    WHERE EDAD >= 20 GROUP BY ESTADO, BARRIO, EDAD ORDER BY EDAD;
    
    SELECT MAX(CANTIDAD) AS CANTIDAD_MAXIMA FROM items_facturas WHERE CODIGO_DEL_PRODUCTO = '1101035';
    
    SELECT COUNT(*) FROM items_facturas WHERE CODIGO_DEL_PRODUCTO = '1101035' AND CANTIDAD = 99;
    
    -- HAVING 
    
    SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabla_de_clientes GROUP BY ESTADO 
    HAVING LIMITE_TOTAL > 300000;
    
    SELECT ENVASE, MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO, 
    SUM(PRECIO_DE_LISTA) AS SUMA_PRECIO
    FROM tabla_de_productos
    GROUP BY ENVASE HAVING SUM(PRECIO_DE_LISTA) >= 80 AND MAX(PRECIO_DE_LISTA) >= 5;
    
    SELECT DNI, COUNT(*) FROM facturas
	WHERE YEAR(FECHA_VENTA) = 2016
	GROUP BY DNI
	HAVING COUNT(*) > 2000;
    
    -- CASE (EVALUA CONDICIONES)
    
    SELECT * FROM tabla_de_productos;
    
    SELECT NOMBRE_DEL_PRODUCTO, PRECIO_DE_LISTA,
		CASE
        WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
        WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'REGULAR'
        ELSE 'BARATO'
	END AS PRECIO
    FROM TABLA_DE_PRODUCTOS;
    
	SELECT ENVASE, SABOR,
		CASE
        WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
        WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'REGULAR'
        ELSE 'BARATO'
	END AS PRECIO, MIN(PRECIO_DE_LISTA) AS PRECIO_MINIMO
    FROM TABLA_DE_PRODUCTOS
    WHERE TAMANO = '700 ML'
    GROUP BY ENVASE, SABOR,
    CASE
        WHEN PRECIO_DE_LISTA >= 12 THEN 'COSTOSO'
        WHEN PRECIO_DE_LISTA >= 5 AND PRECIO_DE_LISTA < 12 THEN 'REGULAR'
        ELSE 'BARATO'
	END
    ORDER BY ENVASE;
    
SELECT NOMBRE,
CASE 
    WHEN YEAR(fecha_de_nacimiento) < 1990 THEN 'Viejos'
    WHEN YEAR(fecha_de_nacimiento) >= 1990 
    AND YEAR(fecha_de_nacimiento) <= 1995 THEN 'Jóvenes' 
    ELSE 'Niños' 
END AS CLASIFICACION_EDAD
FROM tabla_de_clientes;