-- FUNCIONES CON STRINGS

SELECT LTRIM("       MYSQL ES FACIL");
SELECT RTRIM("MYSQL ES FACIL       ");
SELECT TRIM("    MYSQL ES FACIL    ");
SELECT CONCAT("MYSQL ES FACIL,", " ¿NO LO CREES?");
SELECT UPPER("mysql es una bd");
SELECT LOWER("MYSQL ES BUENO");
SELECT SUBSTRING("MYSQL ES UNA BD INTERESANTE.", 14,4);
SELECT CONCAT(NOMBRE, " ", DNI) FROM tabla_de_clientes;

SELECT CONCAT(NOMBRE, " ", DIRECCION_1, " ", CIUDAD, " ", BARRIO, " ", ESTADO) AS COMPLETO FROM tabla_de_clientes;