-- CONVERSION DE DATOS

SELECT CURRENT_TIMESTAMP() AS RESULTADO;
SELECT CONCAT("La fecha y la hora de hoy son: ", CURRENT_TIMESTAMP()) AS FECHA;
SELECT CONCAT("El año es: ", DATE_FORMAT(CURRENT_TIMESTAMP(), "%W, %D/%M/%Y A LAS %T")) AS RESULTADO;
SELECT CONVERT(23.45, CHAR) AS RESULTADO;
SELECT SUBSTRING(CONVERT(23.45, CHAR), 3,1) AS RESULTADO;

SELECT CONCAT("El cliente ", FASE1.NOMBRE, " facturó ", FLOOR(SUM(ITF.CANTIDAD * ITF.PRECIO)), " en el año 2016") AS SENTENCIA
FROM (
    SELECT TC.NOMBRE, F.NUMERO, F.FECHA_VENTA
    FROM TABLA_DE_CLIENTES TC
    INNER JOIN FACTURAS F ON F.DNI = TC.DNI
    WHERE YEAR(F.FECHA_VENTA) = 2016
) FASE1
INNER JOIN ITEMS_FACTURAS ITF ON FASE1.NUMERO = ITF.NUMERO
GROUP BY FASE1.NOMBRE;
