-- UNION DE TABLAS

-- UNION (UNE 2 O MÁS TABLAS. IMPLICITAMENTE EJECUTA DISTINCT)

SELECT DISTINCT BARRIO FROM tabla_de_clientes;

SELECT DISTINCT BARRIO FROM tabla_de_vendedores;

SELECT DISTINCT BARRIO FROM tabla_de_clientes
UNION
SELECT DISTINCT BARRIO FROM tabla_de_vendedores;

-- UNION ALL (UNE 2 O MÁS TABLAS Y NO EJECUTA DISTINCT)

SELECT DISTINCT BARRIO FROM tabla_de_clientes
UNION ALL
SELECT DISTINCT BARRIO FROM tabla_de_vendedores;